# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: node fetch_email.js
    - name: Run maintain.sh
      run: |
        chmod +x ./maintain.sh
        ./maintain.sh
    - name: Commit and push if changed
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Action"
        epoch_time=$(date +%s)
        git checkout -b ghactions-$epoch_time
        git add .
        git commit -m "Automated changes" || exit 0
        git push origin ghactions-$epoch_time
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        title: Automated changes
        body: This is an auto-generated PR with changes made by the GitHub Action.
        branch: ghactions-${{ steps.build.outputs.epoch_time }}
